### ISSUE TITLE
Truck and Trailer in Combine offload mode can't be sent on to sellpoint via continue arrows.

### ISSUE THREAD

**Issue by Tadeloach** [Stephan-S/FS19_AutoDrive#1213]
**AutoDrive Version:** 1.1.0.2
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   Truck and Trailer
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Truck and trailer in combine offload mode can not be sent on to sell point via the two continue on arrows. Truck will only go to sell point if offload percentage set in the menu is reached.

**If applicable - Steps to reproduce the behavior**  
Setup a harvester and vehicle to offload.  Let Autodrive offload the harvester but not  get very full.  Click continue arrows to send to selected sellpoint.  Offloader doesn't do anything.

**Screenshots**

**Comment by Stephan-S** [comment]
Should be fixed now :-)

**Comment by Tadeloach** [comment]
No sir.  I redownloaded 1.1.0.2 about 10 minutes ago.  I still can't get
the truck driver to continue on.  I have my combine running the field.  Hit
the power button on autodrive for the offload vehicle.  He sits there
saying waiting for call.  He is 76% loaded, so I tried the double arrow to
send him on, and nothing happened.  Is there a log or something I can send
you?

**Comment by Tadeloach** [comment]
@Stephan-S Should I be downloading the latest build, or release?  I think I may be confused.

**Comment by Stephan-S** [comment]
latest build

**Comment by Tadeloach** [comment]
@Stephan-S that could be the issue lol.  I am sorry.  WIll download it now.

**Comment by Tadeloach** [comment]
It is fixed.  Thank you sir!
