### ISSUE TITLE
LUA error[BUG]

### ISSUE THREAD

**Issue by Scania1983** [Stephan-S/FS19_AutoDrive#1454]
**AutoDrive Version:** 1.1.0.4   
**Release or Custom Zip:** Release  
**Map (If applicable):** Somewhere in Europe
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
I saved the map once, no problems, then i want to load it again and i get a lua error. It is almost at the bottom of the log.

Error: Running LUA method 'loadMapFinished'.
2020-05-27 20:15 C:/Users/danie/Documents/My Games/FarmingSimulator2019/mods/fs19_autodrive/scripts/Utils/AutoDriveUtilFuncs.lua:132: attempt to perform arithmetic on a nil value

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4690999/log.txt)

Edit: it has something to do with the new autodrive course for the map. I disabled autodrive, removed the autodrive course from the savegame, save the game without autodrive checked, then exit, load the map again with autodrive checked, it starts, when i put the course in the savegame again it gets the lua error again

**Comment by Iwan1803** [comment]
You should try the latest RC. Maybe there are some backward driving routes which can't be handled with 1.1.0.4.

**Comment by Scania1983** [comment]
Ty for your answer, where can I find the rc version?

**Comment by Iwan1803** [comment]
At the bottom: https://github.com/Stephan-S/FS19_AutoDrive

**Comment by Scania1983** [comment]
Thanks, was on mobile searching, will try when I’m home

**Comment by Scania1983** [comment]
It works again, thanks for the help

**Comment by Scania1983** [comment]
Not yet working. If i want to load a course it takes ages to look if there is a course and the camera freezes, there is a course to connect with, but it says it can't find a course. What could be the problem?

I have no error in the log.
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/4697629/log.txt)

**Comment by Axel32019** [comment]
Your last log contains no error, just the normal behavior. Could you please provide a screenshot with routes enabled from the situation where this happens?

**Comment by Scania1983** [comment]
> Your last log contains no error, just the normal behavior. Could you please provide a screenshot with routes enabled from the situation where this happens?


![fsScreen_2020_05_29_22_17_22](https://user-images.githubusercontent.com/65482225/83336970-e309b300-a2b7-11ea-82aa-2891d2d819c7.jpg)

I removed my other maps from the mod map, GC icons and VehicleFruitHud i removed too.

**Comment by Axel32019** [comment]
OK, please check the road network from this point to Feld 04 for the following issues:
- missing connection(s)
- turn angle(s) >90 degree

**Comment by Scania1983** [comment]
I think i found it, there were some mission connections at an intersection and there is a loop course that was causing trouble with calculating i think, i deleted 1 waypoint from the loop and my tractor was driving of, fingers crossed, thank you for the help

**Comment by Iwan1803** [comment]
So problem is solved?

**Comment by Scania1983** [comment]
At the shop it still freeze sometime, the rest works, so no bug or anything, i will close this, thx

**Comment by uded** [comment]
Got the same error on Wild West map.

```
2020-08-30 00:04 Error: Running LUA method 'loadMapFinished'.
2020-08-30 00:04 [...]/FS19_AutoDrive/scripts/Utils/AutoDriveUtilFuncs.lua:132: attempt to perform arithmetic on a nil value
```

No obvious reason, XML seems valid
