### ISSUE TITLE
Issue with Pickup and Deliver mode in 1.0.6.7

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#781]
Tractor reaches the loading point, loads up the trailer, but then wont continue no matter what, it says Cant Reach "destination name".

Also i am getting this error.
2019-11-03 22:27 C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:849: bad argument #1 to 'pairs' (table expected, got nil)

https://youtu.be/apNuh4DxWaA
https://youtu.be/eod42-jRPHQ

**Comment by bojanh66** [comment]
Still same problem and still getting LUA error even with latest source files.
You can see LUA error in 2nd video at 0:03-0:04 seconds.
https://youtu.be/SVeyCv0bX7s
https://youtu.be/IGI5un_Nb7A

**Comment by TyKonKet** [comment]
It should be fixed now.

**Comment by bojanh66** [comment]
No, its not fixed, mode Pickup and Deliver does not work and it causes LUA error.
If i choose Drive only, it works perfect, so the route is good, but something is causing LUA error.
Hopefully it will be fixed, but im curious does anyone else have issue with Pickup and Deliver ?

**Comment by bojanh66** [comment]
Still having error, even with latest commit files.
2019-11-08 09:35 Error: Running LUA method 'update'.
2019-11-08 09:35 C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua:849: bad argument #1 to 'pairs' (table expected, got nil)

I will upload savegame, can you please check if it happens on your PC too ? Tnx

It only happens around farm and farm silo destination points, once it get past those points, it drives normally, but around these points driver locks up and gives LUA error.

Happens only in pickup and delivery mode.
Map is Oakfield, latest version.

[savegame2.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3824267/savegame2.zip)

**Comment by TyKonKet** [comment]
Can you try downloading the latest version? because at the line in which you are reporting the error there is nothing that can generate it so I think you are using an older version.
Are you using the zip downloaded from the release section or did you zip by yourself with the latest files?

**Comment by bojanh66** [comment]
Yes, i tried with latest release version which was released 5 days ago and still having same issue.
And this is how i download latest commit files.
https://youtu.be/1rwWd1s72XE

I tried with default in-game tractor and trailer, also same issue, driver locks up while its around farm / farm silo points, once it gets past them, it drives normally.

**Comment by TyKonKet** [comment]
Ok, if you really want to try with latest commits, you have to manually zip the 'FS19_AutoDrive' folder that you find inside the 'FS19_AutoDrive-master.zip' zip file when you download the repo.
Please try it and let us know.
![image](https://user-images.githubusercontent.com/7534621/68475525-9fbafa80-0228-11ea-917f-55133c4019a3.png)

Please zip only the files inside that folder and not the folder itself.

**Comment by bojanh66** [comment]
It works now, cant believe.
I was always moving zip file from releases folder, but when i zipped files from FS19_AutoDrive folder, it works flawless without LUA error.
Ty very much for your help.

**Comment by TyKonKet** [comment]
No problem, if you move the zip from the releases folder, you get the same version of the release page here on Github 😄

**Comment by bojanh66** [comment]
Yea, i see now, i didnt know that, because when i opened downloaded folder and look at date of modified files, it says it was modified few minutes/ hours ago.
But anyway,i've learned something new today. :)
